{% set name = "std-uritemplate" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/std_uritemplate-{{ version }}.tar.gz
  sha256: 7703a886cce59d155c21b5acf1ad8d48db9f3322de98fa783a8396fbf35cbc06

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - stduritemplate
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/std-uritemplate/std-uritemplate
  summary: std-uritemplate implementation for Python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/std-uritemplate/std-uritemplate
  doc_url: https://github.com/std-uritemplate/std-uritemplate/blob/main/Readme.md

extra:
  recipe-maintainers:
    - xylar
